###
###
### Adicionar isso no arquivo config.yaml
### na pasta assets/config.yaml do seu servidor
###
###

pagseguro:
  # base que vai armazenar 
  # os dados das transacoes
  basededados: ---------

  ## endereco da empresa
  addr-rua: ---------
  addr-numero: ---------
  addr-bairro: ---------
  addr-cep: ---------
  addr-cidade: ---------
  addr-estado: ---------

  ## plano basico e IR
  plan-id: ---------
  plan-reference: ---------
  plan-price: ---------
  ir-reference: ---------
  ir-description: ---------

  ## credenciais de acesso
  credential: ---------
  token: ---------
  
  ## url's basicas
  # url: https://pagseguro.uol.com.br # producao
  # ws: https://ws.pagseguro.uol.com.br # producao
  # stc: https://stc.pagseguro.uol.com.br # producao
  url: https://sandbox.pagseguro.uol.com.br # sandbox
  ws: https://ws.sandbox.pagseguro.uol.com.br # sandbox
  stc: https://stc.sandbox.pagseguro.uol.com.br # sandbox
  redirection-url: ---------
  
  ## url's de funcoes
  create-session: /v2/sessions?email={{email}}&token={{token}}
  cc-brand: https://df.uol.com.br/df-fe/mvc/creditcard/v1/getBin?tk={{sessionID}}&creditCard={{ccBin}}
  cc-token: https://df.uol.com.br/v2/cards
  get-parcelas: /checkout/v2/installments.json?sessionId={{sessionID}}&amount={{amount}}&creditCardBrand={{ccBrand}}
  do-checkout: /v2/transactions?email={{email}}&token={{token}}
  see-checkout: /v3/transactions/{{transactionID}}?email={{email}}&token={{token}}
  do-subscription: /pre-approvals?email={{email}}&token={{token}}
  see-subscription: /pre-approvals/{{subscriptionID}}?email={{email}}&token={{token}}