#!/bin/bash

mvn install:install-file -Dfile=aio-bequiend-1.7.5.jar -DgroupId=aio.bequiend -DartifactId=bequiend -Dversion=1.7.5 -Dpackaging=jar
mvn -T 8 clean install -Dmaven.test.skip=true

cd target/
mvn install:install-file -Dfile=pagseguro-java-backend-1.0.0.jar -DgroupId=com.venosyd -DartifactId=pagseguro-java-backend -Dversion=1.0.0 -Dpackaging=jar