#!/bin/bash

mvn -T 8 clean install -Dmaven.test.skip=true
cd target/
mvn install:install-file -Dfile=pagseguro-java-backend-1.0.0.jar -DgroupId=com.venosyd -DartifactId=pagseguro-java-backend -Dversion=1.0.0 -Dpackaging=jar