#!/bin/bash

## download
curl -LJO https://github.com/venosyd/aio_bequiend/releases/download/1.7.5/aio-bequiend-1.7.5.jar --silent

## instalacao e build
mvn install:install-file -Dfile=aio-bequiend-1.7.5.jar -DgroupId=aio.bequiend -DartifactId=bequiend -Dversion=1.7.5 -Dpackaging=jar

## limpeza
rm aio-bequiend-1.7.5.jar
